// Exact column structure from the provided inventory template
export const INVENTORY_TEMPLATE_COLUMNS = [
  'ASIN',
  'SKU',
  'Title',
  'ROI, %',
  'FBA/FBM Stock',
  'Stock value',
  'Estimated Sales Velocity',
  'Days of stock left',
  'Recommended quantity for reordering',
  'Running out of stock',
  'Reserved',
  'Sent to FBA',
  'Ordered',
  'Time to reorder',
  'Margin',
  'Profit forecast (30 days)',
  'Comment',
  'Marketplace',
  'Target stock range after new order days',
  'FBA buffer days',
  'Manuf. time days',
  'Use a Prep Center',
  'Shipping to Prep Center days',
  'Shipping to FBA days',
  'Box param length',
  'Box param width',
  'Box param height',
  'Box param Units In Box',
  'Color',
  'Size',
  'Multipack size',
  'Item number',
  'FNSKU',
  'Recommended ship-in quantity (by Amazon)',
  'Recommended ship-in date (by Amazon)',
  'Historical days of supply',
  'Supplier SKU',
  'FBA prep. stock Gold Coast',
  'FBA prep. stock Prep center 2 stock',
  'FBA prep. stock Prep center 3 stock',
  'FBA prep. stock Prep center 4 stock',
  'Missed profit (est)'
] as const;

export type InventoryColumn = typeof INVENTORY_TEMPLATE_COLUMNS[number];

export interface InventoryRow extends Record<InventoryColumn, string | number> {}